name: Deploy Portfolio Autom치tico

on:
  push:
    branches:
      - main  # O GitHub Actions ser치 ativado sempre que voc칡 enviar para a branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 游뚴 Pegando o c칩digo atualizado
        uses: actions/checkout@v3

      - name: 游댣 Instalando Node e gerando o Build (Vite)
        run: |
          npm install
          npm run build

      - name: 游 Enviando arquivos para a Staycloud via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/  # Pasta que o Vite gera ap칩s o build
          server-dir: ./public_html/  # Pasta padr칚o de sites no cPanel